### PR TITLE
Chillrx/sweets/init

### PR DESCRIPTION
**Pull request by SweetmanTech**
# Staking Interface for [ChillRx](https://opensea.io/collection/chillrx)
1. `src/contracts/chillrx-staking.json` - ChillRx Staking Contract ABI. 💊 
2. `adapters/chillrx.adapter.ts` - ChillRx Adapter Class. 🎹 
3. `src/component.ts` - Registered ChillRxStakingContractAdapter. 💿

### CODE REVIEW

**Comment by raymondfeng** [comment]
@SweetmanTech Thank you for the contribution. I cleaned up your PR and pushed back.

Please sign off the commit.

**Comment by SweetmanTech** [comment]
@raymondfeng looks good to me 👍 

can you please merge?

**Review by SweetmanTech — COMMENTED** [review]
reviewed ✅ 

can you please merge @raymondfeng ?

**Comment by raymondfeng** [comment]
@SweetmanTech You misunderstood my ask. Please follow instructions at https://docs.pi-hole.net/guides/github/how-to-signoff/.

**Comment by SweetmanTech** [comment]
commit has already been signed off @raymondfeng ....

Screen Shot 2022-10-13 at 7 39 19 PM

what else is blocking this?

**Comment by raymondfeng** [comment]
I'll clean up the PR as you added the old history back.

**Comment by SweetmanTech** [comment]
waiting for your response @raymondfeng 👀

**Pull request merged**
