### PR TITLE
Fix: Remove staked tokens for SuperVerse

### PR DESCRIPTION
**Pull request by blascokoa**
Removed the staked tokens option for superverse, and will let only the stakedPower, not sure why, i wasnt able to select on the UI the staked power instead of the staking tokens, so as after review the contract, that values are complementary, decided to remove the staking tokens and start working only with the stakerPower

### CODE REVIEW

**Comment by blascokoa** [comment]
@raymondfeng can you merge this please?

**Comment by raymondfeng** [comment]
Do you see two items on cc.collab.land?

Screenshot 2024-05-06 at 7 08 15 AM

**Comment by blascokoa** [comment]
hmmm thats interesting, i wasn't able to see 2 contracts there in the past 2 weeks, maybe an issue with cache

**Comment by blascokoa** [comment]
I see it now, will close this PR is not required anymore

**Pull request closed without merging**
